# Generated by Django 5.1.7 on 2025-03-14 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_link', models.URLField(max_length=225)),
                ('facebook_link', models.URLField(max_length=225)),
                ('linkedin_link', models.URLField(max_length=225)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'main_contact',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(max_length=255, unique=True)),
                ('date', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='history/')),
                ('is_visible', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
                'db_table': 'main_history',
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('link', models.URLField(max_length=225)),
                ('image', models.ImageField(upload_to='partner/')),
                ('is_visible', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'main_partner',
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='portfolios/')),
                ('client', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'db_table': 'main_portfolios',
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='services/')),
                ('is_visible', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'main_services',
                'ordering': ('sort', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('role', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='staff/')),
                ('twitter_link', models.URLField(max_length=225)),
                ('facebook_link', models.URLField(max_length=225)),
                ('linkedin_link', models.URLField(max_length=225)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'main_staff',
                'ordering': ('sort', 'first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\+?(38)?\\d{10}$')])),
                ('message', models.TextField(max_length=255)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'main_user_messages',
                'ordering': ('-date_created',),
            },
        ),
    ]
