# Generated by Django 5.1.7 on 2025-03-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
