# Generated by Django 5.1.7 on 2025-03-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='small_description',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
