# Generated by Django 5.1.7 on 2025-03-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_small_description_portfolio_small_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='small_desc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
